alias compose="docker-compose -f service.yml"
alias shell="docker-compose -f service.yml exec"
alias logs="docker-compose -f service.yml logs -f"
alias activate="source .venv/bin/activate"
alias fetch="git fetch --all"
alias prune="git fetch --prune"
alias pull="git pull"
alias checkout="git checkout"