@apiUrl = https://localhost/api

### Create a new user
POST {{ apiUrl }}/create_account
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "data": "data"
}

### Login with the created user
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
  "username": "student_1",
  "password": "passwd"
}

### Create static user
# @name static_user
POST {{ apiUrl }}/static_users
Content-Type: application/json

{
  "username": "staff_1",
  "password": "passwd",
  "groups": "FA"
}

### student account
### Create static user
# @name static_user
POST {{ apiUrl }}/static_users
Content-Type: application/json

{
  "username": "student",
  "password": "stedunt",
  "groups": "ST"
}



### Access secure data (after login)
# @name secure_data
@token = {{login.response.body.token}}
GET {{ apiUrl }}/secure_data
Authorization: Bearer {{ token }}

### Logout the current user
POST {{ apiUrl }}/logout
Content-Type: application/json
Authorization: Bearer {{ token }}

### REQUEST RES
POST {{ apiUrl }}/res
Content-Type: application/json

{
  "name": "jquery"
}

### REQUEST VER
GET {{ apiUrl }}/ver
Content-Type: application/json

### user_data
# @name update_user_data
@token = {{login.response.body.token}}
PUT {{ apiUrl }}/user_info
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "João Souza Silva",
  "phone": "3121286800",
  "address": "Rua Inexistente, 2000",
  "gender": "M",
  "dob": "2024-09-14",
  "img": ""
}


### student accout


### attendance
# @name attendance
@token = {{login.response.body.token}}
GET {{ apiUrl }}/attendance
Content-Type: application/json
Authorization: Bearer {{ token }}