
@apiUrl = https://localhost:5000

### Create a new user
POST {{ apiUrl }}/create_account
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "data": "data"
}

### Login with the created user
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### Login with the created user
# @name user
POST {{ apiUrl }}/users
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "groups": "SU"
}


### Get me
@token = {{login.response.body.token}}

### Access secure data (after login)
GET {{ apiUrl }}/secure-data
Content-Type: application/json
Authorization: Bearer {{ token }}

### Logout the current user
POST {{ apiUrl }}/logout
Content-Type: application/json
Authorization: Bearer {{ token }}



### REQUEST RES
GET {{ apiUrl }}/res
Content-Type: application/json

{
    "name":"version"
}


### REQUEST RES
GET {{ apiUrl }}/ver
Content-Type: application/json
