# server command 
alias compose="docker-compose"
alias shell="docker-compose exec"
alias logs="docker-compose logs -f"
alias fetch="git fetch --all"
alias prune="git fetch --prune"
alias pull="git pull"
alias checkout="git checkout"
alias start="bash run.sh"
alias restart="sudo systemctl restart e-learning.service"
