services:
  db:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d

  angular:
    build:
      context: ./build
      dockerfile: Dockerfile.angular
    container_name: angular
    command: sh run.sh
    restart: unless-stopped
    volumes:
      - ./web/timt:/app
    environment:
      - API_URL=${API_URL}
    working_dir: /app
    ports:
      - 4200:4200

  flask:
    build:
      context: ./build
      dockerfile: Dockerfile.flask
    working_dir: /app
    container_name: flask
    restart: unless-stopped
    command: ["bash", "run.sh"]
    volumes:
      - ./app:/app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_NAME: ${SERVER_NAME}
      BOT_KEY: ${BOT_KEY}
      CHANNEL_ID: ${CHANNEL_ID}
      BOT_ENABLE: ${BOT_ENABLE}
    expose:
      - 5000
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "/dba"
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/timt/dist/timt:/usr/share/nginx/html
    depends_on:
      - db
      - flask
      - phpmyadmin
      - portainer
  
  portainer:
    image: portainer/portainer-ce:latest  # Use the latest Portainer image
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Access to host Docker socket
      - portainer_data:/data  # Persistent storage for Portainer

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - db
      - flask
      - phpmyadmin
      - nginx
      - portainer

volumes:
  portainer_data: