version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: timt#123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  angular:
    build:
      context: .
      dockerfile: Dockerfile.angular
    container_name: angular
    restart: unless-stopped
    volumes:
      - ./web/timt:/app
    working_dir: /app
    ports:
      - 4200:4200
    depends_on:
      - db

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask
    restart: unless-stopped
    command: ["python", "app.py"]
    volumes:
      - ./app:/app
    environment:
      CONFIG_PATH: /app/config.json
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_USER: myuser
      # PMA_PASSWORD: mypassword
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/timt/dist/timt:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - angular
      - flask
      - phpmyadmin
