# Dockerfile.flask

FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY app/requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy application code
COPY . .

# Run the application
CMD ["python", "app.py"]
