services:
  db:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PMA_PORT: 3306
    ports:
      - ${DATABASE_ADMIN_PORT}:80

  flask:
    build:
      context: ./build
      dockerfile: Dockerfile.flask
    working_dir: /app
    restart: always
    command: "bash run.sh"
    dns:
      - 8.8.8.8
    ports:
      - ${API_PORT}:5000
    volumes:
      - ./api:/app
      - ./dotfiles:/home/vscode
    environment:
      SECRET_KEY: ${API_SECRET_KEY}
      DB_HOST: ${DATABASE_HOST}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      SERVER_NAME: ${NAME}
      BOT_KEY: ${BOT_KEY}
      CHANNEL_ID: ${BOT_CHANNEL_ID}
      BOT_ENABLE: ${BOT_ENABLE}
      MAIL: ${MAIL}
      MAIL_KEY: ${MAIL_KEY}

  angular:
    build:
      context: ./build
      dockerfile: Dockerfile.angular
    container_name: angular
    command: "sh run.sh"
    dns:
      - 8.8.8.8
    volumes:
      - ./web/timt:/app
      - ./dotfiles:/home/vscode
    ports:
      - 4200:4200
    environment:
      - MODE=${MODE}
    working_dir: /app
  react:
    build:
      context: ./build
      dockerfile: Dockerfile.react
    container_name: react
    command: "sh run.sh"
    dns:
      - 8.8.8.8
    volumes:
      - ./web/timt:/app
      - ./dotfiles:/home/vscode
    ports:
      - 3000:3000
    environment:
      - MODE=${MODE}
    working_dir: /app
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/timt/www/timt/browser:/usr/share/nginx/html
    ports:
      - ${NGINX_PORT}:80