services:
  db:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PMA_PORT: 3306
      PMA_ALLOW_FRAME: 'true'
      PMA_NO_XFRAME: '1'
    ports:
      - ${DATABASE_ADMIN_PORT}:80

  flask:
    build:
      context: ./docker/build
      dockerfile: Dockerfile.dep.flask
    working_dir: /app
    restart: always
    command: "bash run.sh"
    dns:
      - 8.8.8.8
    ports:
      - ${API_PORT}:5000
    volumes:
      - ./api:/app
    environment:
      SECRET_KEY: ${API_SECRET_KEY}
      DB_HOST: ${DATABASE_HOST}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      SERVER_NAME: ${NAME}
      BOT_KEY: ${BOT_KEY}
      CHANNEL_ID: ${BOT_CHANNEL_ID}
      BOT_ENABLE: ${BOT_ENABLE}
      SMTP_SERVER: ${MAIL_SERVER}
      SMTP_PORT: ${MAIL_SERVER_PORT}
      MAIL: ${MAIL}
      MAIL_KEY: ${MAIL_KEY}

  admin:
    build:
      context: ./docker/build
      dockerfile: Dockerfile.dep.angular
    container_name: admin
    command: "sh run.sh"
    dns:
      - 8.8.8.8
    volumes:
      - ./web/admin:/app
      - ./docker/containers/admin:/home/vscode
    ports:
      - 5173:5173
    expose:
      - 5173
    environment:
      - MODE=${MODE}
    working_dir: /app
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/timt/www/timt/browser:/usr/share/nginx/html
      - ./web/admin/dist/admin/browser:/usr/share/nginx/admin
    ports:
      - ${NGINX_PORT:-80}:80
      - ${ADMIN_PORT:-81}:81

volumes:
  db_data: