services:
  db:
    image: mariadb:local
    container_name: db.timt
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin:local
    container_name: dba.timt
    restart: always
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PMA_PORT: 3306
      PMA_ALLOW_FRAME: 'true'
      PMA_NO_XFRAME: '1'



  flask:
    image: flask:local
    container_name: api.timt
    working_dir: /app
    restart: always
    command: "bash run.sh"
    dns:
      - 8.8.8.8
    user: vscode
    volumes:
      - ./api:/app
      - dotfiles:/home/vscode
    environment:
      SECRET_KEY: ${API_SECRET_KEY}
      DB_HOST: ${DATABASE_HOST}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      SERVER_NAME: ${NAME}
      BOT_KEY: ${BOT_KEY}
      CHANNEL_ID: ${BOT_CHANNEL_ID}
      BOT_ENABLE: ${BOT_ENABLE}
      SMTP_SERVER: ${MAIL_SERVER}
      SMTP_PORT: ${MAIL_SERVER_PORT}
      MAIL: ${MAIL}
      MAIL_KEY: ${MAIL_KEY}

  angular:
    image: angular:local
    container_name: timt
    command: "sh run.sh"
    dns:
      - 8.8.8.8
    volumes:
      - ./web/timt:/app
      - dotfiles:/home/vscode
    # ports:
    #   - 4200:4200
    environment:
      - MODE=${MODE}
    working_dir: /app
  
  admin:
    image: angular:local
    container_name: admin.timt
    command: "sh run.sh"
    dns:
      - 8.8.8.8
    volumes:
      - ./web/admin:/app
      - dotfiles:/home/vscode
    # ports:
    #   - 5173:5173
    expose:
      - 5173
    environment:
      - MODE=${MODE}
    working_dir: /app
  
  mailhog:
    image: mailhog:local
    container_name: mailhog.timt
    # ports:
    #   - "8025:8025"
    #   - "1025:1025"

  # nginx:
  #   image: nginx:local
  #   container_name: timt
  #   volumes:
  #     - ./web/nginx.conf:/etc/nginx/nginx.conf
  #     - ./web/timt/www/timt/browser:/usr/share/nginx/html
  #     - ./web/admin/dist/admin/browser:/usr/share/nginx/admin
  #   # ports:
  #   #   - ${NGINX_PORT:-80}:80
  #   #   - ${ADMIN_PORT:-81}:81

volumes:
  dotfiles: