@apiUrl = http://localhost:5000
# @apiUrl = https://api.timt.in
### REQUEST VER
GET {{ apiUrl }}/ver
Content-Type: application/json

### Login with the created user
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
  "username": "admin@email.com",
  "password": "passwd"
}

### Create static user
# @name static_user
POST {{ apiUrl }}/static_users
Content-Type: application/json

{
  "username": "student@email.com",
  "password": "passwd",
  "groups": "ST",
  "ref": "0"
}

### student account
### Create static user
# @name static_user
POST {{ apiUrl }}/static_users
Content-Type: application/json

{
  "username": "staff@email.com",
  "password": "passwd",
  "groups": "ST",
  "ref": "0"
}


### Logout the current user
POST {{ apiUrl }}/logout
Content-Type: application/json
Authorization: Bearer {{ token }}

### REQUEST RES
POST {{ apiUrl }}/res
Content-Type: application/json

{
  "name": "jquery"
}



### user_data
# @name update_user_data
@token = {{login.response.body.token}}
POST {{ apiUrl }}/user_info
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "João Souza ST",
  "phone": "3121286800",
  "address": "Rua Inexistente, 2000",
  "gender": "M",
  "dob": "2024-09-14",
  "img": ""
}


### SET GPS COD
# @name set_gps_cod
@token = {{login.response.body.token}}
POST {{ apiUrl }}/location
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "lat": 22.381088,
  "lon": 87.794611,
  "dic": 27.0
}

### GET GPS 
### SET GPS COD
# @name set_gps_cod
@token = {{login.response.body.token}}
GET {{ apiUrl }}/location
Content-Type: application/json
Authorization: Bearer {{ token }}


### Attendens
@token = {{login.response.body.token}}
POST {{ apiUrl }}/attendance
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "sem": "4",
    "stream": "3",
    "date": "02/11/2025"
}


#### Attendens by face /attendance/face
# @name att_by_face
@token = {{login.response.body.token}}
POST {{ apiUrl }}/attendance/face
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "image" : "f"
}

#### classes
# @name Classes
@token = {{login.response.body.token}}
POST {{ apiUrl }}/classes
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "id" : "someting"
}

#### STudent
#### add student
# @name student
@token = {{login.response.body.token}}
POST {{ apiUrl }}/student
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "id":"dd621e96aacbcd662ae57a5259790842dcb89a5f046948c51459faf1727e46ce",
  "roll":"2003",
  "reg":"23002",
  "course":"1",
  "semester":"4"
}

#### POSTS
# @name posts
@token = {{login.response.body.token}}
POST {{ apiUrl }}/posts
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "file":"5dbf5e71cadcffdc933f726341ce7252ec20ddf2608d018e2fea351f1efdb037"
}


#### GET ALL Classes
# @name Classes
@token = {{login.response.body.token}}
POST {{ apiUrl }}/users/mng
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "FROM":"student_ac",
  "data":{
    "email":"student@email.com",
    "dob":"10112001",
    "roll":"12345",
    "reg":"29941",
    "course":"BCA",
    "semester": 4
  }
}


######## Info
# @name info_stream
@token = {{login.response.body.token}}

POST {{ apiUrl }}/info/stream
Content-Type: application/json
Authorization: Bearer {{ token }}


{

}

######## Info
# @name info_sem
@token = {{login.response.body.token}}

POST {{ apiUrl }}/info/sem
Content-Type: application/json
Authorization: Bearer {{ token }}

{

  "stream" : 1
}


#### NOTICE
# @name noticeBord
@token = {{login.response.body.token}}
GET {{ apiUrl }}/notice
Content-Type: application/json
Authorization: Bearer {{ token }}

#### NOTICE
# @name CreateNoticeBord
@token = {{login.response.body.token}}
POST {{apiUrl}}/notice
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "title": "Test NOtic6",
    "content": "Do noting",
    "uploadId": null
}

#### NOTICE
# @name FetchNoticeBord
@token = {{login.response.body.token}}
GET {{apiUrl}}/notice
Content-Type: application/json
Authorization: Bearer {{ token }}

##### Download file
GET  = {{apiUrl}}/public/download
Content-Type: application/json

#### password change
POST {{apiUrl}}/users/mng/chpw
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "12345",
  "otp_token": 20,
  "otp": "331151"
}

#### password change otp send
POST {{apiUrl}}/users/mng/chpw
Content-Type: application/json

{
  "email": "admin@email.com"
}

### New Request WebQr
# @name newQR
GET {{apiUrl}}/user/login/weblogin/new
Content-Type: application/json



### Renew Key#
# @name renewQR
GET {{apiUrl}}/user/login/weblogin/xxxx
Content-Type: application/json

#### WEBLOGIN AUTH
POST {{apiUrl}}/user/login/weblogin/auth
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "key": "key"
}


#### info attendence
GET {{apiUrl}}/info/atttendance/today_total
Content-Type: application/json
Authorization: Bearer {{token}}


#### info clases
GET {{apiUrl}}/info/classes/today_total
Content-Type: application/json
Authorization: Bearer {{token}}


##### info notices 
GET {{apiUrl}}/info/notices/month_total
Content-Type: application/json
Authorization: Bearer {{token}}


##### info attence_chart 
POST {{apiUrl}}/info/attendance/stream
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "month": 1
}

###### info edit course

POST {{apiUrl}}/info/course/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
  "name": "BCA",
  "description":"bachelor of computer application",
  "course_fees" : "20000",
  "course_duration" : "4",
  "status":0,
   "id": 1
  
  
}

### info delete api

POST {{apiUrl}}/info/course/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
  
   "id": 1
  
  
}

#### info create course

POST {{apiUrl}}/info/course/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
  "name": "BCAcabc",
  "description":"bachelor of computer application",
  "course_fees" : "20000",
  "course_duration" : "6",
   "status":0
  
  
}


### student fetch 

POST {{apiUrl}}/student/fetch
Content-Type: application/json
Authorization: Bearer {{token}}

{
  
}



### student edit

POST {{apiUrl}}/student/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roll": "1234566",
  "reg":"29941",
  "course" : "2",
  "semester" : "4",
  "status":0,
  "id":"6856baa6e40622c1973a1e12a96ca943f5f49d03dede5cdc4d8386491f651e85"
}


### student migration

POST {{apiUrl}}/student/migration
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "semester" : "6",
  "from_semester": "4"
}

### student delete

POST {{apiUrl}}/student/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id":"6856baa6e40622c1973a1e12a96ca943f5f49d03dede5cdc4d8386491f651e85"
}



### user fetch 

POST {{apiUrl}}/user/fetch
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current":0,
  "max": 15
}



### user edit

POST {{apiUrl}}/user/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": "6856baa6e40622c1973a1e12a96ca943f5f49d03dede5cdc4d8386491f651e85",
  "name": "student2",
  "phone": "8159861554",
  "address": "abcd",
  "gender": "M",
  "birth": "2024-12-12",
  "email": "student_demo@email.com",
  "groups": "ST",
  "status": 0
}




### user delete

POST {{apiUrl}}/user/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id":"6856baa6e40622c1973a1e12a96ca943f5f49d03dede5cdc4d8386491f651e85"
}



#### info create user 

POST {{apiUrl}}/user/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
 "email": "rana@gmail.com" ,
 "passwd": "hi#53" ,
 "groups" : "AD" ,
 "status" : "0 ",
 "name": "Rana" ,
 "phone": "4782789389" ,
 "address": "absd344" ,
 "gender": "F" , 
 "birth": "2003/11/08" ,
 "img": "hello" 

  
}




#### all  user inactive 
POST {{apiUrl}}/user/inactive
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "sem":7
}




### group fetch

POST {{apiUrl}}/group/fetch
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
 
  
}




### group edit

POST {{apiUrl}}/group/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "1",
  "name": "AD",
  "description": "Admin",
  "label": "1"
  
}


#### create groups

POST {{apiUrl}}/group/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name": "Rana" ,
 "code": "AD" ,
 "description": "Adn" ,
 "label": "4" 
 

  
}



### attendence get
@token = {{login.response.body.token}}
POST {{ apiUrl }}/attendance/record
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "sem": "4",
    "stream": "1",
    "year": "2025",
    "month": "",
    "date" : ""
    
    
}


